# Generated by Django 3.2 on 2021-04-23 07:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanRemaining',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_amount', models.IntegerField(verbose_name='TOTAL LOAN AMOUNT')),
                ('amount_remaining', models.IntegerField(verbose_name='AMOUNT REMAINING')),
                ('date_time', models.DateTimeField(default=datetime.datetime(2021, 4, 23, 7, 57, 18, 554239), verbose_name='DATE AND TIME')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.loanmodel', verbose_name='TOTAL LOAN')),
            ],
            options={
                'verbose_name': 'LOAN REMAINING',
                'verbose_name_plural': 'LOAN REMAININGS',
            },
        ),
    ]
