# Generated by Django 3.2 on 2021-04-23 08:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_loanremaining'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanremaining',
            name='amount_paid',
            field=models.IntegerField(default=0, verbose_name='AMOUNT PAID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loanremaining',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 23, 8, 11, 13, 428329), verbose_name='DATE AND TIME'),
        ),
    ]
