# Generated by Django 3.2 on 2021-04-25 09:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_auto_20210423_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanremaining',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 25, 9, 36, 30, 906454), verbose_name='DATE AND TIME'),
        ),
    ]
