# Generated by Django 3.2 on 2021-04-23 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emimodel',
            name='deadline_date',
            field=models.DateField(verbose_name='LAST DATE FOR THIS EMI'),
        ),
    ]
