# Generated by Django 3.2 on 2021-04-23 07:47

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('emi', '0002_alter_emimodel_deadline_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='emimodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emimodel',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='emimodel',
            name='date',
            field=models.DateField(default=datetime.date(2021, 4, 23), verbose_name='DATE'),
        ),
    ]
