# Generated by Django 3.2 on 2021-04-23 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customermodel_mobile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customermodel',
            old_name='cust_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
