# Generated by Django 3.2 on 2021-04-23 06:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20210423_0536'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customermodel',
            options={'verbose_name': 'CUSTOMER', 'verbose_name_plural': 'CUSTOMERS'},
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='address',
            field=models.CharField(max_length=200, verbose_name='ADDRESS'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='EMAIL'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='fname',
            field=models.CharField(max_length=50, verbose_name='FIRST NAME'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='lname',
            field=models.CharField(max_length=50, verbose_name='LAST NAME'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='mobile',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(regex='^\\d{10}$')], verbose_name='MOBILE'),
        ),
    ]
