# Generated by Django 3.2 on 2021-04-25 09:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guaranteer', '0002_auto_20210423_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guaranteermodel',
            name='mobile',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\d{10}$')], verbose_name='MOBILE'),
        ),
    ]
